<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined( 'ABSPATH' ) or die( "Restricted access!" );

/**
 * Register text domain
 *
 * @since 2.1
 */
function SHighlighterForPPHE_textdomain() {
    load_plugin_textdomain( SHPPHE_TEXT, false, SHPPHE_DIR . '/languages/' );
}
add_action( 'init', SHPPHE_PREFIX . '_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  2.1
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function SHighlighterForPPHE_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=' . SHPPHE_SLUG . '.php' ) .'">' . __( 'Settings', SHPPHE_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_' . SHPPHE_BASE, SHPPHE_PREFIX . '_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 2.1
 */
function SHighlighterForPPHE_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, SHPPHE_SLUG . '.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', SHPPHE_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', SHPPHE_PREFIX . '_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 2.1
 */
function SHighlighterForPPHE_register_submenu_page() {
    $menu_title = SHPPHE_NAME;
    $capability = 'manage_options';
    add_options_page( SHPPHE_NAME, $menu_title, $capability, SHPPHE_SLUG, SHPPHE_PREFIX . '_render_submenu_page' );
}
add_action( 'admin_menu', SHPPHE_PREFIX . '_register_submenu_page' );

/**
 * Register settings
 *
 * @since 2.1
 */
function SHighlighterForPPHE_register_settings() {
    register_setting( SHPPHE_SETTINGS . '_settings_group', SHPPHE_SETTINGS . '_settings' );
    register_setting( SHPPHE_SETTINGS . '_settings_group', SHPPHE_SETTINGS . '_service_info' );
}
add_action( 'admin_init', SHPPHE_PREFIX . '_register_settings' );
