<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Register text domain
 *
 * @since 1.0
 */
function SHighlighterForPPHE_textdomain() {
    load_plugin_textdomain( SHPPHE_TEXT, false, SHPPHE_DIR . '/languages/' );
}
add_action( 'init', 'SHighlighterForPPHE_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  1.0
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function SHighlighterForPPHE_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=syntax-highlighter-for-postpage-html-editor.php' ) .'">' . __( 'Settings', SHPPHE_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_'.SHPPHE_BASE, 'SHighlighterForPPHE_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 2.0
 */
function SHighlighterForPPHE_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, 'syntax-highlighter-for-postpage-html-editor.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', SHPPHE_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', 'SHighlighterForPPHE_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 2.0
 */
function SHighlighterForPPHE_register_submenu_page() {
    add_options_page( __( 'Syntax Highlighter for Post/Page HTML Editor', SHPPHE_TEXT ), __( 'Syntax Highlighter for Post/Page HTML Editor', SHPPHE_TEXT ), 'manage_options', 'syntax-highlighter-for-postpage-html-editor', 'SHighlighterForPPHE_render_submenu_page' );
}
add_action( 'admin_menu', 'SHighlighterForPPHE_register_submenu_page' );

/**
 * Register settings
 *
 * @since 2.0
 */
function SHighlighterForPPHE_register_settings() {
    register_setting( 'SHighlighterForPPHE_settings_group', 'SHighlighterForPPHE_settings' );
    register_setting( 'SHighlighterForPPHE_settings_group', 'SHighlighterForPPHE_service_info' );
}
add_action( 'admin_init', 'SHighlighterForPPHE_register_settings' );
